// Code generated by logcopter-gen; DO NOT EDIT.

package matrixhttpcmd

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var log = logcopter.Package("go-go-golems.esper.pkg.commands.matrixhttpcmd")
